#!/bin/bash

# SET SHELL COLOURS
NORMAL="[0;39m"; RED="[1;31m"; YELLOW="[1;33m";WHITE="[1;37m"

# HANDLE SESSION TOKEN/AWS PROFILE
if [ "$AWS_PROFILE" = "" ]
then 
    if [ "$AWS_ACCESS_KEY_ID" != "" ]
    then echo "IAM UserId: $(aws sts get-caller-identity --query 'UserId' --out text)"
    else echo "${RED}""Please set AWS profile name or obtain a session token${NORMAL}"; exit 0
    fi
else 
    echo "AWS_PROFILE: $AWS_PROFILE / $(aws sts get-caller-identity --query 'UserId' --out text)"
fi

function vpc_monkey () {
    for R in $(aws ec2 describe-regions --query "Regions[].RegionName" --out text)
    do
        echo "${WHITE}REGION $R${NORMAL}"
        for V in $(aws --region $R ec2 describe-vpcs --filter "Name=isDefault,Values=true" --query "Vpcs[].VpcId" --out text)
            do
                echo " ${YELLOW}Processing VPC $V${NORMAL}"
                #   1.) Delete the internet-gateway
                for G in $(aws --region $R ec2 describe-internet-gateways --filter "Name=attachment.vpc-id,Values=$V" --query "InternetGateways[].InternetGatewayId" --out text)
                    do
                        echo "  ${RED}Detaching IGW $G${NORMAL}"
                        aws --region $R ec2 detach-internet-gateway --internet-gateway-id $G --vpc-id $V
                        echo "  ${RED}Deleting IGW $G${NORMAL}${NORMAL}"
                        aws --region $R ec2 delete-internet-gateway --internet-gateway-id $G
                done
                #   2.) Delete subnets
                for SN in $(aws --region $R ec2 describe-subnets --filter "Name=vpc-id,Values=$V" --query "Subnets[].SubnetId" --out text)
                    do echo "  ${RED}Deleting $SN${NORMAL}"
                    aws --region $R ec2 delete-subnet --subnet-id $SN
                done
                #   3.) Delete the VPC
            echo " ${RED}Deleting VPC $V${NORMAL}"
            aws --region $R ec2 delete-vpc --vpc-id $V
        done
    done
    # FYI:
    # CANNOT DELETE DEFAULT SGs
    # CANNOT DELETE DEFAULT RTBs
    # CANNOT DELETE DEFAULT NACLs
}

while true; do
    read -p "${RED}Are you sure you want to delete all Default VPCs in ALL regions? ${NORMAL}" yn ; echo ""
    case $yn in
        [Yy]* ) vpc_monkey;echo "";break;;
        [Nn]* ) echo "";exit 0;;
        * ) echo "Please answer yes or no. Press Ctrl-C to break.";echo "";;
    esac
done
